### ISSUE TITLE
Update the version of tf2pulumi installed by ci/install-common-toolchain.sh

### ISSUE THREAD

**Issue by praneetloke** [pulumi/scripts#107]
The default version of `tf2pulumi` installed by the script is 0.6.0 according to [this](https://github.com/pulumi/scripts/blob/master/ci/install-common-toolchain.sh#L37) line. We have the option of overriding that version by setting `TF2PULUMI_VERSION` in the CI environment. But we should also make a new release of `tf2pulumi` and update this script to the latest release.

**Comment by praneetloke** [comment]
There are some issues with the current CI pipeline that are actually addressed with https://github.com/pulumi/tf2pulumi/pull/160. Additionally, https://github.com/pulumi/tf2pulumi/pull/160 also adds support for Python. Once that PR is merged, we can use the latest version that is released from that.

**Comment by praneetloke** [comment]
Updating `tf2pulumi` in CI should fix https://github.com/pulumi/pulumi-aws/issues/945.

**Comment by stack72** [comment]
Closed via #110
