### ISSUE TITLE
Fail publishing when dev packages are depended upon

### ISSUE THREAD

**Issue by joeduffy** [pulumi/scripts#17]
We recently had an issue where we published a non-dev package that had dev dependencies. This is an easy mistake to make, however should be illegal, as it causes all sorts of trouble for consumers.

This feels like something we could check for in `ci/publish-tfgen-package`, or the related scripts, and fail the publication with an error when detected.

**Comment by ellismg** [comment]
Should be fixed with https://github.com/pulumi/scripts/pull/26
