### ISSUE TITLE
govendor-override will put `master` in Gopkg.toml` even when vendor folder upstream is locked to specific commit

### ISSUE THREAD

**Issue by lukehoban** [pulumi/scripts#23]
When trying out the Packet provider,  this block from its `vendor.json` leads to a constraint to `master` being added in `Gopkg.toml`.  However, there have been breaking changes in master for that package, and that is not a sufficiently strong constraint to map to the vendored versions in upstream - which is in practice locked to a 14 day old commit to master.

```
		{
			"checksumSHA1": "PSqb/5tR0vhk3mKgYry32qMkfL8=",
			"path": "github.com/packethost/packngo",
			"revision": "9442574c66d7186bc2afe9e372837c339eb0376b",
			"revisionTime": "2018-11-30T10:03:47Z",
			"version": "master",
			"versionExact": "master"
		},
```

**Comment by stack72** [comment]
We don't use this anymore - we can close this out
