### ISSUE TITLE
Stop using Python 2.7 in our infrastructure

### ISSUE THREAD

**Issue by ellismg** [pulumi/scripts#37]
In CI, `pip` often means "pip on Python 2.7", this is causing a bunch of crazy warnings like the following:

"DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."

We should ensure we are using python 3 everywhere, since the use of python 3 is now a hard requirement of Pulumi.

**Comment by lukehoban** [comment]
I believe this is done - if it is not - please open an issue with links to where we are using Python 2.
