### ISSUE TITLE
Intermittent aws s3 cp failures during publishing

### ISSUE THREAD

**Issue by ellismg** [pulumi/scripts#9]
We’ve seen transient issues during publishing like the following:

copy failed: s3://eng.pulumi.com/releases/pulumi/linux/amd64/d04acf4da157855450016a41ceb51971ff8dbee4.tgz to s3://eng.pulumi.com/releases/pulumi/linux/amd64/master.tgz An error occurred (InvalidArgument) when calling the UploadPartCopy operation: Range specified is not valid for source object of size: 26817341

We should probably add some retry logic to the aws s3 cp step.

**Comment by lukehoban** [comment]
I don't think we've seen this in the last year.
